# Generated by Django 4.1.12 on 2024-02-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='info',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=2),
        ),
    ]
